# Generated by Django 4.2.5 on 2024-02-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app', '0003_alter_profile_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
