# Generated by Django 4.2.5 on 2024-02-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app', '0005_expense_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expens_type',
            new_name='expense_type',
        ),
    ]
